language: c
compiler:
- gcc
script:
- "./build.sh"
deploy:
  provider: s3
  access_key_id: AKIAIFA6CFFPLWRUO2OQ
  secret_access_key:
    secure: z8E6U7YggjC/c6GlAhT8Zbybb78AC2fKhgNRNN1+kQ0/NNtVHCCeJSq2O0OOhkGcZkM34wgpubGk+BkENrFNvXigxcINEZaBAVKO05MI4mkA/4n+Kc/NXlt2deaB96PwtmGNBo3WgqMq9m5I1BDgxNcruqOpC+LEHMcAl1qoJCMh3MK/2+BdC/ng7CdArHzO2QgJVRBZVY4niIwigrBPCTRHcy6pJdxjGi4CkIYt+3B3s1KQBKVY7waGjMb1tg6oKxnpo5AU2197XFrxWnv8VEgTEWGtQn3imDS2CESJ7+Wgdyj8N08Z2R8Ut9+DNYHWpVPOsGSZW882UyRqTCCiALavN36Ob8yBljg8TwK5b6GsWONckbXBEVJEgpGQWHyoW5FmQO3sT+v/UJeA0R6vTuwyh3xTVdkFGVoOREQ7YPY/rVHKr7vxZwUkhMJYbQR+E0MBNpFDS8Z8GQL6jEAndWoLmEKy9pEjL/8FH4y5Hmt4P4R9GiwlTNqhy/oU8d2UFRA1NyxQ08VmZqqu6cZxwrJUA6QM5URH05qj/tnk50sSQfbSETQelALSef5GaAKP1M3cg9jiakgX2wvDegmiJsTfu3H9Bw/CtzjlP4gKZ2+LwV4iryfrNe3atchlej6hgiTeDpkPeVz02IOEPIk7uV3RF58Jx7qSrC8Y0VIWgmQ=
  skip_cleanup: true
  bucket: ota.clockwise.ee
  acl: public_read
  region: us-west-2
  local_dir: dist
  on:
    repo: 2ndalpha/mqtt-h801-light
